### ISSUE TITLE
mica-core使用报错Incompatible argument to function

### ISSUE THREAD

**Issue by fengyie007** [lets-mica/mica#14]
spring 5.0.15，非spring-boot
mica-core 1.2.1
请问报以下错误是啥问题啊？

ParameterizedMessage[messagePattern=prePageRecentContacts has error. bizIds: {}, type: {}, offset: {}, limit: {}, stringArgs=[[u6880965], 1, 0, 15, java.lang.IllegalStateException: Unable to load cache item], throwable=java.lang.IllegalStateException: Unable to load cache item] java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.dreamlu.mica.core.beans.MicaBeanCopier$Generator.create(MicaBeanCopier.java:136)
	at net.dreamlu.mica.core.beans.MicaBeanCopier.lambda$create$0(MicaBeanCopier.java:77)
	at net.dreamlu.mica.core.beans.MicaBeanCopier$$Lambda$174/957806619.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at net.dreamlu.mica.core.beans.MicaBeanCopier.create(MicaBeanCopier.java:71)
	at net.dreamlu.mica.core.beans.MicaBeanCopier.create(MicaBeanCopier.java:65)
	at net.dreamlu.mica.core.utils.BeanUtil.copy(BeanUtil.java:156)
	at net.dreamlu.mica.core.utils.BeanUtil.copy(BeanUtil.java:135)
	at net.dreamlu.mica.core.utils.$.copy($.java:2169)
Caused by: java.lang.VerifyError: (class: org/springframework/cglib/empty/Object$$MicaBeanCopierByCGLIB$$3e7270c9, method: copy signature: (Ljava/lang/Object;Ljava/lang/Object;Lorg/springframework/cglib/core/Converter;)V) Incompatible argument to function
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:467)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)

**Comment by fengyie007** [comment]
知道原因了，是bean里面有 Timestamp类型字段，这个能支持下么？

**Comment by ChunMengLu** [comment]
类型转换？？？

**Comment by ChunMengLu** [comment]
**备忘**：(字节码如下)

```java
public class Object$$AbstractBeanCopierByCGLIB$$eaac9f7e extends AbstractBeanCopier {
  public void copy(Object paramObject1, Object paramObject2, Converter paramConverter) {
    Userx userx = (Userx)paramObject2;
    User user = (User)paramObject1;
    userx.setTimestamp((Timestamp)user.getTimestamp());
  }
}
```

**Comment by fengyie007** [comment]
java.util.Date赋值到java.sql.Timestamp类型报错，反过来是没问题的。

**Comment by ChunMengLu** [comment]
java.util.Date赋值到java.sql.Timestamp类型有问题天经地义哈

Timestamp 是 Date 的子类，Date 哪知道 Timestamp 里面扩展了什么，当然不能直接赋值。

**Comment by fengyie007** [comment]
嗯 我是说在你修复之前生成的generator代码是有问题的。会直接把Date类型赋值给Timestamp类型。
1.2.2版本啥时候能发布啊

**Comment by ChunMengLu** [comment]
v1.2.2 已发
